trigger: none

resources:
  repositories:
  - repository: nucodex
    type: github
    name: Ref12/NuCodex
    endpoint: Ref12
    trigger:
      batch: true
      branches:
        include:
        - opensrc/current
  - repository: azdevagent
    type: github
    name: Xollective/AzDevAgent
    endpoint: Ref12

pool:
  vmImage: windows-latest

variables:
- group: ref12vars
- group: github-agents

jobs:
- template: .azdev/run-with-agents.yml@azdevagent
  parameters:
    image: windows-latest
    jobs:
    - job: opensrc
      steps:
      - checkout: nucodex
        path: s/nucodex
        persistCredentials: true
      - checkout: self
        persistCredentials: true
        path: s/xocodex
      - pwsh: |
          $PSNativeCommandUseErrorActionPreference = $true
          git branch opensrc/current
        displayName: Create branch
        workingDirectory: $(Build.SourcesDirectory)/nucodex      
      - pwsh: |
          $PSNativeCommandUseErrorActionPreference = $true
          git remote add nucodex "$(Build.SourcesDirectory)/nucodex"

          git fetch --all

          git push origin nucodex/opensrc/current:refs/heads/main --force
        displayName: Push changes to xocodex/main
        workingDirectory: $(Build.SourcesDirectory)/xocodex      